#!/bin/sh

#
# This script file is the entry point to ci.miranetworks.net build/test process.
#
# It is executed by jenkins, from the root directory
#


    echo "running cibuild to test"
 
    $coverage = new PHP_CodeCoverage;
    $coverage->start('test/phpunit/unit/strtolowerTest.php');
    $coverage->stop();

    $writer = new PHP_CodeCoverage_Report_Clover;
    $writer->process($coverage, 'phpunit-report/clover.xml');

    $writer = new PHP_CodeCoverage_Report_HTML;
    $writer->process($coverage, 'phpunit-report/code-coverage-report');

exit 0
