#!/bin/sh

#
# This script file is the entry point to ci.miranetworks.net build/test process.
#
# It is executed by jenkins, from the root directory
#


    echo "running cibuild to test"
    phpunit -c app
  
exit 0
